name: Build & Test CupNight Circuit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  forge-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: "stable"
      
      - name: Run Forge build
        run: |
          cd ${GITHUB_WORKSPACE}
          forge build --size

  forge-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: "stable"
      
      - name: Run Forge tests
        run: |
          cd ${GITHUB_WORKSPACE}
          forge test -vvv


